"""schema inicial

Revision ID: 0cb5d87006c6
Revises: 
Create Date: 2026-06-21 17:41:46.761398
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0cb5d87006c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=False),
    sa.Column('account_type', sa.Enum('human', 'agent', name='account_type'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('api_token_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_account_type'), 'users', ['account_type'], unique=False)
    op.create_index(op.f('ix_users_api_token_hash'), 'users', ['api_token_hash'], unique=False)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    op.create_table('follows',
    sa.Column('follower_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('followee_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('author_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR().with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index('ix_posts_feed', 'posts', ['created_at', 'parent_id'], unique=False)
    op.create_index(op.f('ix_posts_parent_id'), 'posts', ['parent_id'], unique=False)
    if op.get_bind().dialect.name == "postgresql":
        op.create_index('ix_posts_search', 'posts', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('likes',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('post_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_like')
    )
    # ### end Alembic commands ###

    # Trigger de full-text: mantém posts.search_vector sincronizado com o
    # conteúdo (apenas no Postgres; ignorado em outros dialetos).
    if op.get_bind().dialect.name == "postgresql":
        # asyncpg não aceita múltiplos comandos num mesmo prepared statement,
        # então cada statement vai em sua própria chamada op.execute().
        op.execute(
            """
            CREATE OR REPLACE FUNCTION posts_tsvector_update() RETURNS trigger AS $$
            BEGIN
              NEW.search_vector := to_tsvector('english', COALESCE(NEW.content, ''));
              RETURN NEW;
            END
            $$ LANGUAGE plpgsql;
            """
        )
        op.execute("DROP TRIGGER IF EXISTS trg_posts_tsvector ON posts;")
        op.execute(
            """
            CREATE TRIGGER trg_posts_tsvector BEFORE INSERT OR UPDATE ON posts
            FOR EACH ROW EXECUTE FUNCTION posts_tsvector_update();
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS trg_posts_tsvector ON posts;")
        op.execute("DROP FUNCTION IF EXISTS posts_tsvector_update();")
    op.drop_table('likes')
    if op.get_bind().dialect.name == "postgresql":
        op.drop_index('ix_posts_search', table_name='posts', postgresql_using='gin')
    op.drop_index(op.f('ix_posts_parent_id'), table_name='posts')
    op.drop_index('ix_posts_feed', table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('follows')
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_api_token_hash'), table_name='users')
    op.drop_index(op.f('ix_users_account_type'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
